// packages/angular/src/scroll.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
  ViewEncapsulation,
} from "@angular/core";
import { Scroll, ScrollMode, ScrollPosition, ScrollState } from "@mr-scroll/core";

@Component({
  selector: "mr-scroll",
  templateUrl: "./scroll.html",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ScrollComponent implements OnInit, AfterViewInit, OnDestroy {
  private _scroll: Scroll;

  @Input() mode?: ScrollMode;

  @Input() topThreshold?: number;

  @Input() bottomThreshold?: number;

  @Input() leftThreshold?: number;

  @Input() rightThreshold?: number;

  @Input() showOnHover?: boolean;

  @Output() scrolled = new EventEmitter<{ left: number; top: number }>();

  @Output() topReached = new EventEmitter<void>();

  @Output() bottomReached = new EventEmitter<void>();

  @Output() leftReached = new EventEmitter<void>();

  @Output() rightReached = new EventEmitter<void>();

  @Output() positionHChanged = new EventEmitter<ScrollPosition>();

  @Output() positionAbsoluteHChanged = new EventEmitter<ScrollPosition>();

  @Output() stateHChanged = new EventEmitter<ScrollState>();

  @Output() positionVChanged = new EventEmitter<ScrollPosition>();

  @Output() positionAbsoluteVChanged = new EventEmitter<ScrollPosition>();

  @Output() stateVChanged = new EventEmitter<ScrollState>();

  @ViewChild("content", { static: true }) _content: ElementRef<HTMLElement>;

  constructor(private _el: ElementRef<HTMLElement>, private _zone: NgZone) {}

  get scroll() {
    return this._scroll;
  }

  ngOnInit() {
    this._scroll = new Scroll(this._el.nativeElement, this._content.nativeElement, {
      mode: this.mode,
      topThreshold: this.topThreshold,
      bottomThreshold: this.bottomThreshold,
      leftThreshold: this.leftThreshold,
      rightThreshold: this.rightThreshold,
      showOnHover: this.showOnHover,
    });

    // Events that will normally trigger change detection.
    const delegatedEvents = [
      "topReached",
      "bottomReached",
      "leftReached",
      "rightReached",
      "positionHChanged",
      "positionAbsoluteHChanged",
      "stateHChanged",
      "positionVChanged",
      "positionAbsoluteVChanged",
      "stateVChanged",
    ];
    // Events that won't trigger change detection. Change detection should be handled by the consumer.
    const delegatedEventsOutsideNgZone = ["scrolled"];

    for (const eventName of delegatedEvents) {
      this._scroll[eventName].subscribe((x: any) => {
        const e = this[eventName] as EventEmitter<any>;
        // Avoid calling zone.run if there are no subscribers to avoid triggering change detection
        if (e.observers.length) {
          this._zone.run(() => {
            e.emit(x);
          });
        }
      });
    }

    for (const eventName of delegatedEventsOutsideNgZone) {
      this._scroll[eventName].subscribe((x: any) => {
        const e = this[eventName] as EventEmitter<any>;
        e.emit(x);
      });
    }
  }

  ngAfterViewInit() {
    this._zone.runOutsideAngular(() => {
      this._scroll.initialize();
    });
  }

  ngOnDestroy() {
    this._scroll.destroy();
  }
}

// packages/vue2/src/scroll.vue
<template>
  <div ref="hostRef">
    <div ref="contentRef">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop, Ref } from "vue-property-decorator";
import { Scroll, ScrollMode } from "@mr-scroll/core";

@Component
export default class ScrollComponent extends Vue {
  private _scroll!: Scroll;

  @Prop() mode?: ScrollMode;
  @Prop() topThreshold?: number;
  @Prop() bottomThreshold?: number;
  @Prop() leftThreshold?: number;
  @Prop() rightThreshold?: number;
  @Prop() showOnHover?: boolean;

  @Ref("hostRef") readonly _hostRef!: HTMLDivElement;
  @Ref("contentRef") readonly _contentRef!: HTMLDivElement;

  get scroll() {
    return this._scroll;
  }

  mounted() {
    this._scroll = new Scroll(this._hostRef, this._contentRef, {
      mode: this.mode,
      topThreshold: this.topThreshold,
      bottomThreshold: this.bottomThreshold,
      leftThreshold: this.leftThreshold,
      rightThreshold: this.rightThreshold,
      showOnHover: this.showOnHover,
    });

    const delegatedEvents = [
      "scrolled",
      "topReached",
      "bottomReached",
      "leftReached",
      "rightReached",
      "positionHChanged",
      "positionAbsoluteHChanged",
      "stateHChanged",
      "positionVChanged",
      "positionAbsoluteVChanged",
      "stateVChanged",
    ];
    for (const eventName of delegatedEvents) {
      (this._scroll as any)[eventName].subscribe((x: any) => {
        this.$emit(eventName, x);
      });
    }

    this._scroll.initialize();
  }

  unmounted() {
    this._scroll.destroy();
  }
}
</script>
